# Generated by Django 2.2 on 2019-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1, max_length=200),
        ),
    ]
