# Generated by Django 2.2 on 2019-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190410_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=200),
        ),
    ]
